spring:
  datasource:
    url: jdbc:postgresql://ecommerce-db.cxssym888kzn.ap-southeast-2.rds.amazonaws.com:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0  # Start version numbering at 0
    out-of-order: true  # Allow out-of-order migrations
    validate-on-migrate: false
  sql:
    init:
      mode: never
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000,
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
  #Login with social media
outbound:
  identity:
    client-id: ${CLIENT_ID:default-client-id}
    client-secret: ${CLIENT_SECRET:default-client-secret}
redirect-uri: ${REDIRECT_URI}

logging:
  level:
    root: ERROR
    com.hcmus: INFO
    org:
      hibernate:
        SQL: OFF
      springframework:
        # jdbc: DEBUG
        web: DEBUG
        data: DEBUG
        boot:
          autoconfigure:
            data:
              rest: DEBUG
            orm: DEBUG
        security: DEBUG
    
server:
  port: 8080
  servlet:
    context-path: /api/v1
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: matkhau
    key-alias: haquocbao.id.vn
# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
    display-request-duration: true
    doc-expansion: none
  packages-to-scan: com.hcmus.ecommerce_backend
  paths-to-match: /**
  

auth:
  keys:
    public-key-path: classpath:keys/public.pem
    private-key-path: classpath:keys/private.pem

app:
  frontend-url: ${FRONTEND_URL}
